### ISSUE TITLE
dem里面的增量更新在mac端有问题

### ISSUE THREAD

**Issue by EmberYu** [xuxingeren/vue-cli-electron#2]
问题：增量更新在mac端无法使用。

复现步骤：
1. npm run build:test:mac。安装这个包0.0.1
2. 修改env.test的版本号位 0.0.2
3. npm run build:test:mac。将app.zip，update.json,update.exe放到同一个路径下起一个http-server。
4. 打开安装的0.0.1的包，检查增量更新，包更新检测完自动退出，重新打开，版本号依旧为0.0.1。再次检测，再次自动退出，一直循环。。

想问下这个问题应该怎么解决呀。我试了下app.unpacked方法也是这样子的

**Comment by xuxingeren** [comment]
exe更新是针对于win系统下的，mac系统无uac限制，可直接替换，查考[评论](https://juejin.cn/post/6953791929314181151)

**Comment by xuxingeren** [comment]
> 问题：增量更新在mac端无法使用。
> 
> 复现步骤：
> 
> 1. npm run build:test:mac。安装这个包0.0.1
> 2. 修改env.test的版本号位 0.0.2
> 3. npm run build:test:mac。将app.zip，update.json,update.exe放到同一个路径下起一个http-server。
> 4. 打开安装的0.0.1的包，检查增量更新，包更新检测完自动退出，重新打开，版本号依旧为0.0.1。再次检测，再次自动退出，一直循环。。
> 
> 想问下这个问题应该怎么解决呀。我试了下app.unpacked方法也是这样子的

exe更新是针对于win系统下的，mac系统无uac限制，可直接替换，查考[评论](https://juejin.cn/post/6953791929314181151)

**Comment by EmberYu** [comment]
> > 问题：增量更新在mac端无法使用。
> > 复现步骤：
> > 
> > 1. npm run build:test:mac。安装这个包0.0.1
> > 2. 修改env.test的版本号位 0.0.2
> > 3. npm run build:test:mac。将app.zip，update.json,update.exe放到同一个路径下起一个http-server。
> > 4. 打开安装的0.0.1的包，检查增量更新，包更新检测完自动退出，重新打开，版本号依旧为0.0.1。再次检测，再次自动退出，一直循环。。
> > 
> > 想问下这个问题应该怎么解决呀。我试了下app.unpacked方法也是这样子的
> 
> exe更新是针对于win系统下的，mac系统无uac限制，可直接替换，查考[评论](https://juejin.cn/post/6953791929314181151)

**Comment by EmberYu** [comment]
我今天上午试了下您的那个方法一替换app.unpacked。替换成功了（可以在Resource里面看到app.unpacked文件夹更新了新的文件），但是重启后electron是白屏，因为是build的包，也没法看到主进程是不是有错误。明天我再试一次。

顺便问下unpacked包替换这个方法应该对windows和mac都试用吧。

**Comment by xuxingeren** [comment]
> 我今天上午试了下您的那个方法一替换app.unpacked。替换成功了（可以在Resource里面看到app.unpacked文件夹更新了新的文件），但是重启后electron是白屏，因为是build的包，也没法看到主进程是不是有错误。明天我再试一次。
> 
> 顺便问下unpacked包替换这个方法应该对windows和mac都试用吧。

都适用，请查考博客的[步骤](https://xuxin123.com/electron/increment-update1/)，看你哪一步缺失，或者是版本号我是12.0，白屏主要检测为加载策略修改后打包安装，看安装后是否正常打开->打增量包手动替换app.asar.unpacked，看是否能启动->最后用代码进行替换逻辑。可以使用[vscode调试主进程](https://www.electronjs.org/docs/tutorial/debugging-vscode)查看错误

**Comment by EmberYu** [comment]
> > 我今天上午试了下您的那个方法一替换app.unpacked。替换成功了（可以在Resource里面看到app.unpacked文件夹更新了新的文件），但是重启后electron是白屏，因为是build的包，也没法看到主进程是不是有错误。明天我再试一次。
> > 顺便问下unpacked包替换这个方法应该对windows和mac都试用吧。
> 
> 都适用，请查考博客的[步骤](https://xuxin123.com/electron/increment-update1/)，看你哪一步缺失，或者是版本号我是12.0，白屏主要检测为加载策略修改后打包安装，看安装后是否正常打开->打增量包手动替换app.asar.unpacked，看是否能启动->最后用代码进行替换逻辑。可以使用[vscode调试主进程](https://www.electronjs.org/docs/tutorial/debugging-vscode)查看错误

试了下手动替换是可以正常用的，但是用代码就白屏，尝试把downloadFile和reload分成两步操作又没问题了。初步怀疑是文件覆盖后立即执行`webContents.reloadIgnoringCache`的原因，在`webContents.reloadIgnoringCache`方法加了个300ms的延时发现可以正常增量更新了，感谢大佬

![image](https://user-images.githubusercontent.com/16729152/135197036-a11456e0-6c2f-47fe-ae2a-2894c9158e52.png)
